### ISSUE TITLE
Error while running this demo

### ISSUE THREAD

**Issue by XikerWu** [chroming/sh_house_price#1]
hello, thanks for you devotion. I am really interested in this demo. However, something might be wrong while I ran the demo code. Could you please help me to fix it?

$ python sh_price.py
本程序用于计算赶集上海二手区房价，单位万/平米
每个区对应代码如下：
0：显示上海所有区单独的平均房价；
1：浦东新区；
2：闵行区；
3：徐汇区；
4：长宁区；
5：普陀区；
6：静安区；
7：卢湾区；
8：黄浦区；
9：闸北区；
a：虹口区；
b：杨浦区；
c：宝山区；
d：嘉定区；
e：青浦区；
f：松江区；
g：金山区；
h：奉贤区；
i：南汇区；
j：崇明区；
k：上海周边；

请输入需要查询的区代码,可一次输入多个代码：0
您输入的区域为：上海所有区域
Traceback (most recent call last):
  File "sh_price.py", line 127, in <module>
    get_area()
  File "sh_price.py", line 116, in get_area
    get_price(numbe)
  File "sh_price.py", line 107, in get_price
    print (area[numb]+"共获取二手房数量："+str(i)+"，平均房价为："+str(round(float(sum_pric)/float(i),2))+"万元每平方")
ZeroDivisionError: float division by zero

**Comment by chroming** [comment]
I test the code today，It work properly. The error you got is because the code can't get the right information from the web. You can check the url 'http://wap.ganji.com/sh/fang5/pudongxinqu/o' with your brower whether the display is normal.

**Comment by XikerWu** [comment]
@chroming when I enter 0, it can only return one result and then no more return. What worse, I run this code again and enter 0 again, it even return nothing. So strange!
...
请输入需要查询的区代码,可一次输入多个代码：0
您输入的区域为：上海所有区域
浦东新区共获取二手房数量：236，平均房价为：4.65万元每平方
您输入的区域为：上海所有区域
Traceback (most recent call last):
  File "sh_price.py", line 127, in <module>
    get_area()
  File "sh_price.py", line 116, in get_area
    get_price(numbe)
  File "sh_price.py", line 107, in get_price
    print (area[numb]+"共获取二手房数量："+str(i)+"，平均房价为："+str(round(float(sum_pric)/float(i),2))+"万元每平方")
ZeroDivisionError: float division by zero

**Comment by XikerWu** [comment]
btw, the URL can be open successfully in any time.

**Comment by chroming** [comment]
maybe the website ganji.com has some error when return page. I had update the code today, now you can get the return page after got this error.

**Comment by chroming** [comment]
Just try the updated code : ）

**Comment by ngmanhei** [comment]
Still not OK, and it returns:
请输入需要查询的区代码，可一次输入多个代码: 0
您输入的区域为：上海所有区域
浦东新区共获取二手房数量：262，平均房价为：4.9万元每平方
获取失败！请使用浏览器检查http://wap.ganji.com/sh/fang5/minhang/o是否能正常显示！
<script type='text/javascript'>var img = new Image();img.src ='http://analytics.ganji.com/mp.gif?ip=10.1.2.95&iscookie=&sid=&ua=&refer=&gjchver=&url=http%3A%2F%2Fwap.ganji.com%2Fsorry%2Fconfirm.php%3Ffrom%3Dwap%26continue%3Dhttp%253a%252f%252fwap.ganji.com%252fsh%252ffang5%252fminhang%252fo49&ifid=&ca_kw=-&gjver=&city=&gc=/all_cate/verify/-/-/op&user_id=&reqid=&uuid=0xfb3509266b44832288c23a1a98a1030';</script><script type='text/javascript'>window.GJ_M_PAGE_CONFIG = 'ip=10.1.2.95&iscookie=&sid=&ua=&refer=&gjchver=&url=http%3A%2F%2Fwap.ganji.com%2Fsorry%2Fconfirm.php%3Ffrom%3Dwap%26continue%3Dhttp%253a%252f%252fwap.ganji.com%252fsh%252ffang5%252fminhang%252fo49&ifid=&ca_kw=-&gjver=&city=&gc=/all_cate/verify/-/-/op&user_id=&reqid=&uuid=0xfb3509266b44832288c23a1a98a1030';</script><script src='http://sta.ganjistatic1.com/att/project/touch/h5_log/tracker_v2.__1463645586__.js'></script><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta http-equiv="Cache-Control" content="no-cache"/>
<meta name="viewport" content="initial-scale=1.0;  minimum-scale=1.0; maximum-scale=1.0" />
<meta name="MobileOptimized" content="240"/>
<meta name="format-detection" content="telephone=no"/>     
<script type="text/javascript" src="http://sta.ganji.com/cgi/ganji_sta.php?file=ganji"></script>
<title>反爬虫页面</title>
......

**Comment by XikerWu** [comment]
still not ok, but thanks a lot!

**Comment by li-jp** [comment]
爬取数据的时候会遭遇反爬虫策略，因为返回的内容中有一段： 

<div style="color:red;">您的浏览器可能没有启用cookie，可能会不能通过验证。</div> <form action="/sorry/wapcheckcode.php" method="get" class="pc-content">
  <div>亲爱的用户，您访问的速度太快</p><p>了，请输入验证码再继续访问:</div>

这种情况就很尴尬了

**Comment by chroming** [comment]
@AsTimeGoseBy 确实如此，这段代码并没有做反爬虫处理，只是一个即兴之作，要考虑反爬虫需要做不少工作
